Repository ansible-community/molecule-gce, pull requests merged in 2021-08, with the labels that each got.

#7 Default branch rename to main
  .github/CODEOWNERS
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  README.rst
  tox.ini
Labels: bug

#10 Require google.cloud collection
  molecule_gce/driver.py
  setup.cfg
Labels: feature

#11 Adopt src based repository layout
  .ansible-lint
  setup.cfg
  src/molecule_gce/__init__.py
  src/molecule_gce/cookiecutter/cookiecutter.json
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.md
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/files/windows_auth.py
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/handlers/main.yml
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/prepare.yml
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/requirements.yml
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/tasks/create_linux_instance.yml
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/tasks/create_windows_instance.yml
  src/molecule_gce/driver.py
  src/molecule_gce/test/__init__.py
  src/molecule_gce/test/functional/.ansible-lint
  src/molecule_gce/test/functional/__init__.py
  src/molecule_gce/test/functional/conftest.py
  src/molecule_gce/test/functional/test_func.py
  src/molecule_gce/test/test_driver.py
Labels: bug

#13 Fix required_collections bug
  src/molecule_gce/driver.py
Labels: bug

#15 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#14 Fix dependendencies and refresh README
  README.md
  setup.cfg
Labels: bug, docs

#16 Remove dependency on oauth2client
  setup.cfg
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/files/windows_auth.py
  src/molecule_gce/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/tasks/create_windows_instance.yml
Labels: bug
